Fix the issue of "unexpected keyword argument 'constructor'"
There is interface change in the new release of openstacksdk (bug/1755465)
which caused the following failure for os-client-config:
"TypeError: get_session_client() got an unexpected keyword argument 'constructor'.

Further more, it's recommending to use openstacksdk directly instead of
using os-client-config.

This commit is to use remove os-client-config but use openstacksdk
directly.